name: Starter workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

  schedule:
    - cron: '0 0 * * 0' # every sunday midnight

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Test
      run: npm test

    - name: Run linters
      uses: wearerequired/lint-action@v2
      with:
        eslint: true
        prettier: true

    - name: Print message
      run: |
        "Hello [username of the user who initiated the run]. You pushed to [repository_name] at $(date)."